export const bannerData = {
  alertWeb: "https://video.truemeds.in/Images/Upi-dweb-announcement.jpg",
  callDetails: "08069808861",
  homeGeneric: [
    {
      id: 8,
      active: true,
      header: "Now save your money with substitute",
      description: "Now save your money with substitute",
      image:
        "https://video.truemeds.in/video/are_rising_medicine_cost_causing_trouble.mp4",
      webUrl:
        "https://video.truemeds.in/video/are_rising_medicine_cost_causing_trouble.mp4",
      redirectTo: null,
      eventName: "thumbnail",
      drugType: null,
      ranking: 1,
      type: "WEBSITE",
      redirectUrl: null,
      subType: "HOME_GENERIC",
      thumbnailUrl:
        "https://assets.truemeds.in/Images/m-banners-home-page-4.jpg",
    },
  ],
  alert: "https://video.truemeds.in/Images/UPI-mweb.jpg",
  upiInfoUrl: [],
  banners: [
    {
      id: 5,
      active: true,
      header: "Saving on all your healthcare medicines",
      description: "Saving on all your healthcare medicines",
      image: "https://assets.truemeds.in/Images/dwebbanner2.jpeg",
      webUrl: "https://assets.truemeds.in/Images/Content/Med_Web_New.jpg",
      redirectTo: "search",
      eventName: "bachatbadhegi",
      drugType: null,
      ranking: 2,
      type: "WEBSITE",
      redirectUrl: null,
      subType: "BANNERS",
      thumbnailUrl: null,
    },
    {
      id: 7,
      active: true,
      header: "Save upto 51% with substitute",
      description: "Save upto 51% with substitute",
      image: "https://assets.truemeds.in/Images/dwebbanner1.jpeg",
      webUrl: "https://assets.truemeds.in/Images/W-BANNER1.jpg",
      redirectTo: "search",
      eventName: "save51_banner",
      drugType: null,
      ranking: 1,
      type: "WEBSITE",
      redirectUrl: null,
      subType: "BANNERS",
      thumbnailUrl: null,
    },
    {
      id: 10,
      active: true,
      header: "Mobikwik Cashback",
      description: "Mobikwik Cashback ",
      image: "https://assets.truemeds.in/Images/dwebbanner4.jpeg",
      webUrl: "https://video.truemeds.in/Images/mobiwik_web3.jpeg",
      redirectTo: "search",
      eventName: "mobiwikcashback",
      drugType: null,
      ranking: 3,
      type: "WEBSITE",
      redirectUrl: null,
      subType: "BANNERS",
      thumbnailUrl: null,
    },
    {
      id: 13,
      active: true,
      header: "Haircare Banner",
      description: "Haircare",
      image: "https://assets.truemeds.in/Images/dwebbanner3.jpeg",
      webUrl: "https://assets.truemeds.in/Images/dwebbanner3.jpeg",
      redirectTo: "search",
      eventName: "haircarebanner",
      drugType: null,
      ranking: 3,
      type: "WEBSITE",
      redirectUrl: null,
      subType: "BANNERS",
      thumbnailUrl: null,
    },
  ],
  generic: [],
};
