export const getDeliveryCharges = {
  srcTypeMaster: [
    {
      serialId: 369,
      name: "PRODUCT_SOURCE_TYPE",
      value: "ASSISTED PRODUCT ADD",
      description: null,
      active: true,
      createdOn: 1678445843000,
      createdBy: null,
      lastModifiedOn: 1678445843000,
      lastModifiedBy: null,
    },
    {
      serialId: 327,
      name: "PRODUCT_SOURCE_TYPE",
      value: "CHECKER PRODUCT ADD",
      description: null,
      active: true,
      createdOn: 1664267934000,
      createdBy: null,
      lastModifiedOn: 1664267934000,
      lastModifiedBy: null,
    },
    {
      serialId: 308,
      name: "PRODUCT_SOURCE_TYPE",
      value: "CSR PRODUCT ADD",
      description: null,
      active: true,
      createdOn: 1658491104000,
      createdBy: null,
      lastModifiedOn: 1658491104000,
      lastModifiedBy: null,
    },
    {
      serialId: 302,
      name: "PRODUCT_SOURCE_TYPE",
      value: "CUSTOMER APP PRODUCT ADD",
      description: null,
      active: true,
      createdOn: null,
      createdBy: null,
      lastModifiedOn: null,
      lastModifiedBy: null,
    },
    {
      serialId: 303,
      name: "PRODUCT_SOURCE_TYPE",
      value: "CUSTOMER WEBSITE PRODUCT ADD",
      description: null,
      active: true,
      createdOn: null,
      createdBy: null,
      lastModifiedOn: null,
      lastModifiedBy: null,
    },
    {
      serialId: 304,
      name: "PRODUCT_SOURCE_TYPE",
      value: "DOCTOR PRODUCT ADD",
      description: null,
      active: true,
      createdOn: null,
      createdBy: null,
      lastModifiedOn: null,
      lastModifiedBy: null,
    },
    {
      serialId: 305,
      name: "PRODUCT_SOURCE_TYPE",
      value: "OPERATION PRODUCT ADD",
      description: null,
      active: true,
      createdOn: null,
      createdBy: null,
      lastModifiedOn: null,
      lastModifiedBy: null,
    },
    {
      serialId: 307,
      name: "PRODUCT_SOURCE_TYPE",
      value: "PHARMACIST PRODUCT ADD",
      description: null,
      active: true,
      createdOn: 1658491104000,
      createdBy: null,
      lastModifiedOn: 1658491104000,
      lastModifiedBy: null,
    },
  ],
  deliveryOnAmount: "299",
  deliveryCharge: "49",
  deliveryChargeSubs: "49",
  baseDiscount: 20.0,
  deliveryOnAmountSubs: "299",
};
