export const mobileMaster = {
  srcTypeMaster: [
    {
      serialId: 369,
      name: "PRODUCT_SOURCE_TYPE",
      value: "ASSISTED PRODUCT ADD",
      description: null,
      active: true,
      createdOn: 1678445843000,
      createdBy: null,
      lastModifiedOn: 1678445843000,
      lastModifiedBy: null,
    },
    {
      serialId: 327,
      name: "PRODUCT_SOURCE_TYPE",
      value: "CHECKER PRODUCT ADD",
      description: null,
      active: true,
      createdOn: 1664267934000,
      createdBy: null,
      lastModifiedOn: 1664267934000,
      lastModifiedBy: null,
    },
    {
      serialId: 308,
      name: "PRODUCT_SOURCE_TYPE",
      value: "CSR PRODUCT ADD",
      description: null,
      active: true,
      createdOn: 1658491104000,
      createdBy: null,
      lastModifiedOn: 1658491104000,
      lastModifiedBy: null,
    },
    {
      serialId: 302,
      name: "PRODUCT_SOURCE_TYPE",
      value: "CUSTOMER APP PRODUCT ADD",
      description: null,
      active: true,
      createdOn: null,
      createdBy: null,
      lastModifiedOn: null,
      lastModifiedBy: null,
    },
    {
      serialId: 303,
      name: "PRODUCT_SOURCE_TYPE",
      value: "CUSTOMER WEBSITE PRODUCT ADD",
      description: null,
      active: true,
      createdOn: null,
      createdBy: null,
      lastModifiedOn: null,
      lastModifiedBy: null,
    },
    {
      serialId: 304,
      name: "PRODUCT_SOURCE_TYPE",
      value: "DOCTOR PRODUCT ADD",
      description: null,
      active: true,
      createdOn: null,
      createdBy: null,
      lastModifiedOn: null,
      lastModifiedBy: null,
    },
    {
      serialId: 305,
      name: "PRODUCT_SOURCE_TYPE",
      value: "OPERATION PRODUCT ADD",
      description: null,
      active: true,
      createdOn: null,
      createdBy: null,
      lastModifiedOn: null,
      lastModifiedBy: null,
    },
    {
      serialId: 307,
      name: "PRODUCT_SOURCE_TYPE",
      value: "PHARMACIST PRODUCT ADD",
      description: null,
      active: true,
      createdOn: 1658491104000,
      createdBy: null,
      lastModifiedOn: 1658491104000,
      lastModifiedBy: null,
    },
  ],
  deliveryOnAmount: "299",
  subsOptReasons: [
    {
      reasonId: 150,
      orderDetailsStatistics: [],
      name: "SUBS_OPT_REASONS",
      value: "Yes",
      active: true,
      isValid: null,
      smsTemplateId: null,
      parentReasonId: null,
      shuffle: null,
    },
    {
      reasonId: 151,
      orderDetailsStatistics: [],
      name: "SUBS_OPT_REASONS",
      value: "No",
      active: true,
      isValid: null,
      smsTemplateId: null,
      parentReasonId: null,
      shuffle: null,
    },
    {
      reasonId: 152,
      orderDetailsStatistics: [],
      name: "SUBS_OPT_REASONS",
      value: "Closed",
      active: true,
      isValid: null,
      smsTemplateId: null,
      parentReasonId: null,
      shuffle: null,
    },
  ],
  searchTypeMaster: [
    {
      serialId: 359,
      name: "DISEASE1",
      value: "in disease",
      description: null,
      active: true,
      createdOn: 1676895109000,
      createdBy: null,
      lastModifiedOn: 1676895109000,
      lastModifiedBy: null,
    },
    {
      serialId: 360,
      name: "DISEASE2",
      value: "in disease",
      description: null,
      active: true,
      createdOn: 1676895109000,
      createdBy: null,
      lastModifiedOn: 1676895109000,
      lastModifiedBy: null,
    },
    {
      serialId: 361,
      name: "DISEASE3",
      value: "in disease",
      description: null,
      active: true,
      createdOn: 1676895109000,
      createdBy: null,
      lastModifiedOn: 1676895109000,
      lastModifiedBy: null,
    },
    {
      serialId: 364,
      name: "MOLECULE_NAME",
      value: "in salt",
      description: null,
      active: true,
      createdOn: 1676895109000,
      createdBy: null,
      lastModifiedOn: 1676895109000,
      lastModifiedBy: null,
    },
    {
      serialId: 363,
      name: "ORIGINAL_COMPANY_NM",
      value: "in company",
      description: null,
      active: true,
      createdOn: 1676895109000,
      createdBy: null,
      lastModifiedOn: 1676895109000,
      lastModifiedBy: null,
    },
    {
      serialId: 365,
      name: "ORIGINAL_MOTHER_BRAND",
      value: "in brand",
      description: null,
      active: true,
      createdOn: 1676895109000,
      createdBy: null,
      lastModifiedOn: 1676895109000,
      lastModifiedBy: null,
    },
    {
      serialId: 362,
      name: "OTC_DISEASE",
      value: "in disease",
      description: null,
      active: true,
      createdOn: 1676895109000,
      createdBy: null,
      lastModifiedOn: 1676895109000,
      lastModifiedBy: null,
    },
    {
      serialId: 367,
      name: "OTC_SUB_CATEGORY",
      value: "in category",
      description: null,
      active: true,
      createdOn: 1676905508000,
      createdBy: null,
      lastModifiedOn: 1676905508000,
      lastModifiedBy: null,
    },
    {
      serialId: 366,
      name: "SUPER_CATEGORY",
      value: "in category",
      description: null,
      active: true,
      createdOn: 1676895109000,
      createdBy: null,
      lastModifiedOn: 1676895109000,
      lastModifiedBy: null,
    },
  ],
  deliveryCharge: "49",
  deliveryChargeSubs: "49",
  baseDiscount: 20.0,
  delayTimeInSecs: "10",
  deliveryOnAmountSubs: "299",
};
